# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

localrules: all,
    genome, transcriptome, genesets, 
    decoys, concatenate_genome_transcriptome

include: "rules/common.smk"


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.
        'resources/salmon_index',
        'resources/txp2gene.tsv',
        expand(["results/alevin/{sample}/alevin/quants_mat.gz",
                "results/plots/{sample}/barcode_rank.svg"],
               sample=samples['sample'])


include: "rules/salmon.smk"
include: "rules/alevin.smk"
include: "rules/qc.smk"
include: "rules/other.smk"
